# Generated by Django 3.1.7 on 2021-03-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WindowsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='updatesublist',
            name='feature_update_sublist',
        ),
        migrations.RenameModel(
            old_name='FeatureUpdateSublist',
            new_name='UpdateSecurity',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UpdateSublist',
        ),
        migrations.AddField(
            model_name='windowsupdate',
            name='windows_update_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.updatesecurity'),
        ),
        migrations.AddField(
            model_name='featureupdate',
            name='update_security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.updatesecurity'),
        ),
    ]
