# Generated by Django 3.1.7 on 2021-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20210327_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowsupdate',
            old_name='windows_update_choice',
            new_name='update_security',
        ),
    ]
