# Generated by Django 3.1.7 on 2021-03-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20210327_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureupdate',
            old_name='update_security',
            new_name='update_security_2',
        ),
        migrations.RenameField(
            model_name='windowsupdate',
            old_name='update_security',
            new_name='update_security_1',
        ),
    ]
