# Generated by Django 3.1.7 on 2021-03-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20210327_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureupdate',
            old_name='update_security_2',
            new_name='update_security',
        ),
        migrations.RenameField(
            model_name='windowsupdate',
            old_name='update_security_1',
            new_name='update_security',
        ),
    ]
