# Generated by Django 3.1.7 on 2021-03-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20210327_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsupdate',
            name='update_security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.updatesecurity'),
        ),
        migrations.CreateModel(
            name='Error2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.featureupdate')),
            ],
        ),
        migrations.CreateModel(
            name='Error1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('windows_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.windowsupdate')),
            ],
        ),
        migrations.CreateModel(
            name='About2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.featureupdate')),
            ],
        ),
        migrations.CreateModel(
            name='About1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('windows_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.windowsupdate')),
            ],
        ),
    ]
