# Generated by Django 3.1.7 on 2021-03-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20210327_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatesecurity',
            options={'verbose_name_plural': 'UpdateSecurity'},
        ),
    ]
