# Generated by Django 3.1.7 on 2021-03-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20210327_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About2',
            new_name='AboutFeatureUpdate',
        ),
        migrations.RenameModel(
            old_name='About1',
            new_name='AboutWindowsUpdate',
        ),
        migrations.RenameModel(
            old_name='Error2',
            new_name='FeatureUpdateError',
        ),
        migrations.RenameModel(
            old_name='Error1',
            new_name='WindowsUpdateError',
        ),
    ]
