# Generated by Django 3.1.7 on 2021-03-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20210327_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutwindowsupdate',
            name='windows_update',
        ),
        migrations.RemoveField(
            model_name='featureupdateerror',
            name='feature_update',
        ),
        migrations.RemoveField(
            model_name='windowsupdateerror',
            name='windows_update',
        ),
        migrations.DeleteModel(
            name='AboutFeatureUpdate',
        ),
        migrations.DeleteModel(
            name='AboutWindowsUpdate',
        ),
        migrations.DeleteModel(
            name='FeatureUpdateError',
        ),
        migrations.DeleteModel(
            name='WindowsUpdateError',
        ),
    ]
