# Generated by Django 3.1.7 on 2021-04-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_auto_20210408_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('apps_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.apps')),
                ('devices_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.devices')),
                ('network_internet_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.networkinternet')),
                ('system_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.system')),
                ('tcn_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.tcn')),
                ('update_security_var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.updatesecurity')),
            ],
        ),
    ]
