# Generated by Django 3.1.7 on 2021-04-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
