# Generated by Django 3.1.7 on 2021-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0013_delete_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesecurity',
            name='description',
            field=models.TextField(default='no data'),
        ),
    ]
