# Generated by Django 3.1.7 on 2021-04-18 09:29

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_auto_20210417_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_yes', models.TextField()),
                ('camera_no', models.TextField()),
                ('printers', models.TextField()),
                ('sound_yes', models.TextField()),
                ('sound_no', models.TextField()),
                ('vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='UpdateSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus_about', models.TextField()),
                ('antivirus_issues', models.TextField()),
                ('bitlocker_about', models.TextField()),
                ('bitlocker_yes', models.TextField()),
                ('bitlocker_no', models.TextField()),
                ('fu_about', models.TextField()),
                ('fu_errors', models.TextField()),
                ('wu_about', models.TextField()),
                ('wu_errors', models.TextField()),
                ('vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name_plural': 'UpdateSecurity',
            },
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
