# Generated by Django 3.1.7 on 2021-04-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_auto_20210417_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='UpdateSecurity',
        ),
    ]
