# Generated by Django 3.1.7 on 2021-04-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_auto_20210417_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatesecurity',
            options={'verbose_name_plural': 'UpdateSecurity'},
        ),
    ]
