# Generated by Django 3.1.7 on 2021-04-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_auto_20210418_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
