# Generated by Django 3.1.7 on 2021-04-18 09:44

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_delete_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_yes', models.TextField()),
                ('camera_no', models.TextField()),
                ('printers', models.TextField()),
                ('sound_yes', models.TextField()),
                ('sound_no', models.TextField()),
                ('vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
