# Generated by Django 3.1.7 on 2021-04-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='updatesecurity',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
